server:
  port: ${tomcat.port:8888}
spring:
  profiles:
    active: persist,dev
  resources:
    static-locations:
      - classpath:/static/
      - classpath:/templates/

  mvc:
    view:
      prefix: /templates/
      suffix: .html
    static-path-pattern: /xx/**
  application:
    name: e-welfare