spring:
  cache:
    type: redis
  datasource:
    url: jdbc:mysql://db.haproxy.cbest.gam:36601/e_welfare?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: jav_tclife_rw
    password: 3uUacFIf3PDoBy
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      maxActive: 200
      minIdle: 1
      testOnBorrow: true
      testOnReturn: false
      validationQuery: SELECT 1
  redis:
    lettuce:
      pool:
        max-idle: 30
        max-active: 500
        min-idle: 2
        max-wait: 1000
    timeout: 5000
    database: 0
    password: v6z82Ebfc7I1
    host: redis.cbest.gam
    port: 6399

logging:
  file:
    path: /data/Logs/e-welfare-account
  level:
    root: info
    com.welfare.persist.mapper: info

encrypt:
  file: ${config.file:classpath:config/config.properties}
e-welfare:
  distributed-lock:
    enabled: true
  barcode:
    expire-for-notification: 3600
    expire-for-pay: 240
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

platformUser:
  url: http://welfare-internal.kube.cbestcd.com/backend-api/tc/store

shopping:
  url: http://welfare-internal.kube.cbestcd.com/backend-api/rpc-base

cbest:
  pay:
    url: http://192.1.30.160:8000/gateway
    appId: olife
    appKey: e400233f4a719304ce189cde2aeaae98
  dmall:
    url: http://dmall.e-cbest.com
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 300000
xxl:
  job:
    admin:
      addresses: http://172.30.37.47:8334/
    executor:
      appname: e-welfare-account
      ip:
      port: 9898
      logpath: /data/Logs/e-welfare-account/jobhandler/
      logretentiondays: 30
    accessToken:

notification:
  url: http://welfare-internal.kube.cbestcd.com
  targetPath: https://welfare-app.sjgo365.com/tc/redirect?target=center

wo-life:
  url: http://113.204.98.245:8900/livingroom