spring:
  cache:
    type: redis
  datasource:
    url: jdbc:mysql://192.1.30.186:3306/e-welfare-0208?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: mysql@123
  redis:
    lettuce:
      pool:
        max-idle: 30
        max-active: 8
        min-idle: 2
        max-wait: 1000
    timeout: 5000
    cluster:
      nodes:
        - 192.1.30.186:7000
        - 192.1.30.186:7001
        - 192.1.30.186:7002
        - 192.1.30.186:7003
        - 192.1.30.186:7004
        - 192.1.30.186:7005
    database: 0
    #password: msxfMarketing
logging:
  file:
    path: /home/finance/Logs/e-welfare-account.e-cbest.lotest
  level:
    root: info
    com.welfare.persist.mapper: debug
encrypt:
  file: ${config.file:classpath:config/config.properties}
e-welfare:
  distributed-lock:
    enabled: true
  barcode:
    expire: 180
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
platformUser:
  url:
shopping:
  url:

cbest:
  pay:
    url: http://192.1.30.71:9999/gateway
    appId: yufu
    appKey: e4716980da4382e1f4cc6ee4bb640277
  dmall:
    url: http://192.1.34.24
exclude-header-interceptor:
  - /swagger*/**
  - /doc.html*
  - /error*
  - /index
  - /**/*.css
  - /**/*.js
  - /**/*.png
  - /**/*.jpg
  - /**/*.jpeg
  - /**/*.ico
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 300000
xxl:
  job:
    admin:
      addresses: http://172.30.37.35:8180/
    executor:
      appname: e-welfare-account
      ip:
      port: 9898
      logpath: /home/finance/Logs/e-welfare-account.e-cbest.lotest/jobhandler/
      logretentiondays: 30
    accessToken:

notification:
  url: http://test-welfare-internal.kube.cbestcd.com
  targetPath: https://test-welfare-app.sjgo365.com/tc/redirect?target=center