spring:
  profiles: online
logging:
  level:
    root: info
  file:
    path: /home/honour/Logs/e-welfare-account.e-cbest.lo
encrypt:
  file: ${config.file:file:/home/finance/Config/e-welfare-account.e-cbest.lo/config.properties}