spring:
  datasource:
    url: jdbc:mysql://192.1.30.186:3306/cbest_employee_card?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: mysql@123
logging:
  file:
    path: /home/finance/Logs/e-welfare-account.e-cbest.lotest
  level:
    root: info
#encrypt:
  #file: ${config.file:file:/home/finance/Config/e-welfare-account.e-cbest.lotest/config-test.properties}
e-welfare:
  distributed-lock:
    enabled: true
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0