spring:
  datasource:
    url: jdbc:mysql://192.1.30.186:3306/cbest_employee_card?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: mysql@123
logging:
  file:
    path: /home/finance/Logs/e-welfare-merchant.e-cbest.lotest
  level:
    root: info
#encrypt:
  #file: ${config.file:classpath:config/config.properties}

cbest:
  oss:
    config:
      bucket: sjgo-img-test
  pay:
    url: http://192.1.30.71:9999/gateway
    appId: yufu
    appKey: e4716980da4382e1f4cc6ee4bb640277
    notifyUrl: http://xxx/accountDepositRecord/payNotify

cdn:
  server: http://img-test.sjgo365.com

e-welfare:
  distributed-lock:
    enabled: true
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0


platformUser:
  url: http://test-welfare-app.sjgo365.com/shop-api/tc/store

shopping:
  url: http://test-welfare-internal.kube.cbestcd.com/backend-api/rpc-base



feign:
  client:
    config:
      #default代表所有服务
      default:
        #feign客户端建立连接超时时间
        connect-timeout: 10000
        #feign客户端建立连接后读取资源超时时间
        read-timeout: 30000
      #而service-test表示当调用service-test这个服务时，用下面的配置
      #service-test:
       # connect-timeout: 10000
        #read-timeout: 20000