spring:
  profiles:
    active: persist,dev
  application:
    name: e-welfare-merchant
server:
  port: 10016

cbest:
  oss:
  config:
    accessKey: lF3iXaqMbr9f3GEdPJeN
    secretKey: KqMaYYENOqD8JBZUhqgBhOddVYc5Y1Pd1pAJRoA2
    keyPrefix: e-welfare/