spring:
  profiles:
    active: persist,dev
  application:
    name: e-welfare-merchant
  mvc:
      date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  port: 10016
cbest:
  oss:
    config:
      accessKey: lF3iXaqMbr9f3GEdPJeN
      secretKey: KqMaYYENOqD8JBZUhqgBhOddVYc5Y1Pd1pAJRoA2
      keyPrefix: e-welfare/



