spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://192.1.30.186:3306/e-welfare-0208?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: mysql@123
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  redis:
    lettuce:
      pool:
        max-idle: 30
        max-active: 8
        min-idle: 2
        max-wait: 1000
    timeout: 5000
    cluster:
      nodes:
        - 192.1.30.186:7000
        - 192.1.30.186:7001
        - 192.1.30.186:7002
        - 192.1.30.186:7003
        - 192.1.30.186:7004
        - 192.1.30.186:7005
logging:
  file:
    path: D:/home/finance/Logs/e-welfare-account.e-cbest.lotest
  level:
    root: info
encrypt:
  file: ${config.file:classpath:config/config.properties}

cbest:
  oss:
    config:
      bucket: sjgo-img-test

  pay:
      url: http://192.1.30.71:9999/gateway
      appId: yufu
      appKey: e4716980da4382e1f4cc6ee4bb640277
      notifyUrl: http://xxx/accountDepositRecord/payNotify
  dmall:
      url: http://172.30.37.22:4000
cdn:
  server: http://img-test.sjgo365.com
e-welfare:
  distributed-lock:
    enabled: true
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
  mapper-locations: classpath:/mapper/*.xml

platformUser:
  url: http://test-welfare-app.sjgo365.com/shop-api/tc/store

shopping:
  url: http://test-welfare-internal.kube.cbestcd.com/backend-api/rpc-base

exclude-header-interceptor:
  - /swagger*/**
  - /doc.html*
  - /error*
  - /index
  - /**/*.css
  - /**/*.js
  - /**/*.png
  - /**/*.jpg
  - /**/*.jpeg
  - /**/*.ico

feign:
  client:
    config:
      #default代表所有服务
      default:
        #feign客户端建立连接超时时间
        connect-timeout: 10000
        #feign客户端建立连接后读取资源超时时间
        read-timeout: 30000
      #而service-test表示当调用service-test这个服务时，用下面的配置
      #service-test:
       # connect-timeout: 10000
        #read-timeout: 20000