spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://192.1.30.186:3306/cbest_employee_card?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: mysql@123
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    lettuce:
      pool:
        max-idle: 30
        max-active: 8
        min-idle: 2
        max-wait: 1000
    timeout: 5000
    cluster:
      nodes:
        - 192.1.30.186:7000
        - 192.1.30.186:7001
        - 192.1.30.186:7002
        - 192.1.30.186:7003
        - 192.1.30.186:7004
        - 192.1.30.186:7005
logging:
  file:
    path: /home/finance/Logs/e-welfare-account.e-cbest.lotest
  level:
    root: info
encrypt:
  file: ${config.file:classpath:config/config.properties}

cbest:
  oss:
    config:
      bucket: sjgo-img-test
      accessKey: lF3iXaqMbr9f3GEdPJeN
      secretKey: KqMaYYENOqD8JBZUhqgBhOddVYc5Y1Pd1pAJRoA2
      keyPrefix: e-welfare/
cdn:
  server: http://img-test.sjgo365.com
e-welfare:
  distributed-lock:
    enabled: true
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
  mapper-locations: classpath:/mapper/*.xml

platformUser:
  url: