spring:
  datasource:
    url: jdbc:mysql://${db.server}:${db.port}/${db.name}?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: ${db.username}
    password: ${db.pwd}
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
