spring:
  profiles: test
logging:
  level:
    root: info
  file:
    path: /home/finance/Logs/e-welfare-merchant.e-cbest.lotest
encrypt:
  file: ${config.file:file:/home/finance/Config/e-welfare-merchant.e-cbest.lotest/config-test.properties}