spring:
  datasource:
    url: jdbc:mysql://db.haproxy.cbest.gam:36601/e_welfare?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: jav_tclife_rw
    password: 3uUacFIf3PDoBy
    type: com.alibaba.druid.pool.DruidDataSource
    maxActive: 200
    minIdle: 1
    testOnBorrow: true
    testOnReturn: false
    validationQuery: SELECT 1
  redis:
    lettuce:
      pool:
        max-idle: 30
        max-active: 500
        min-idle: 2
        max-wait: 1000
    timeout: 5000
    database: 0
    password: v6z82Ebfc7I1
    host: redis.cbest.gam
    port: 6399
  kafka:
    servers: 192.1.30.236:6667,192.1.30.237:6667,192.1.30.238:6667
    topic: order-info
    group-id: welfare
    offset: earliest

logging:
  file:
    path: /data/Logs/e-welfare-settlement
  level:
    root: info
    com.welfare.persist.mapper: info

encrypt:
  file: ${config.file:classpath:config/config.properties}
e-welfare:
  distributed-lock:
    enabled: true
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

platformUser:
  url:

cbest:
  pay:
    url: http://192.1.30.160:8000/gateway
    appId: yufu
    appKey: e4716980da4382e1f4cc6ee4bb640277
    notifyUrl: http://xxx/accountDepositRecord/payNotify
  oss:
    config:
      bucket: sjgo-img

xxl:
  job:
    admin:
      addresses: http://172.30.37.47:8334/
    executor:
      appname: e-welfare-settlement
      ip:
      port: 9888
      logpath: /data/Logs/e-welfare-settlement/jobhandler/
      logretentiondays: 30
    accessToken:
pos:
  onlines: 1001
cdn:
  server: http://img.sjgo365.com