spring:
  datasource:
    url: jdbc:mysql://db.haproxy.cbest.gam:36601/e_welfare?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: jav_tclife_rw
    password: 3uUacFIf3PDoBy
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      maxActive: 200
      minIdle: 1
      testOnBorrow: true
      testOnReturn: false
      validationQuery: SELECT 1
  redis:
    lettuce:
      pool:
        max-idle: 30
        max-active: 500
        min-idle: 2
        max-wait: 1000
    timeout: 5000
    database: 0
    password: v6z82Ebfc7I1
    host: redis.cbest.gam
    port: 6399
  kafka:
    servers: 192.1.30.236:6667,192.1.30.237:6667,192.1.30.238:6667
    topic: order-info
    group-id: welfare
    offset: earliest

logging:
  file:
    path: /data/Logs/e-welfare-settlement
  level:
    root: info
    com.welfare.persist.mapper: info

encrypt:
  file: ${config.file:classpath:config/config.properties}
e-welfare:
  distributed-lock:
    enabled: true
  account:
    url: http://welfareaccount.api.cbest.gam
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

platformUser:
  url: http://welfare-internal.kube.cbestcd.com/backend-api/tc/store

shopping:
  url: http://welfare-internal.kube.cbestcd.com/backend-api/rpc-base

cbest:
  pay:
    url: http://192.1.30.160:8000/gateway
    appId: olife
    appKey: e400233f4a719304ce189cde2aeaae98
    notifyUrl: http://xxx/accountDepositRecord/payNotify
  oss:
    config:
      bucket: sjgo-img
  dmall:
    url: http://dmall.e-cbest.com
xxl:
  job:
    admin:
      addresses: http://172.30.37.47:8334/
    executor:
      appname: e-welfare-settlement
      ip:
      port: 9888
      logpath: /data/Logs/e-welfare-settlement/jobhandler/
      logretentiondays: 30
    accessToken:
pos:
  onlines: 1001
cdn:
  server: http://img.sjgo365.com

merchant:
  url: http://welfaremerchant.api.cbest.gam

service-mirror:
  url: http://192.1.30.96

ftp:
  enabled: true
  host: paycheckftp.e-cbest.com
  port: 2112
  user: pay_tiancheng
  password: 4m+Hatccc
  default-path: /bills

rocketmq:
  name-server: a.broker.rocketmq.cbest.gam:9876;b.broker.rocketmq.cbest.gam:9876
  topic:
    order-online: MSGCENTRAL_APP_WELFARE_ORDER_STATUS_CHANGE
    order-online-after-sale: MSGCENTRAL_APP_WELFARE_ORDER_AFTERSALE_CHANGED
    account-deduction-detail: E-WELFARE-ACCOUNT-DEDUCTION-DETAIL