server:
  port: ${tomcat.port:8080}

spring:
  profiles:
    active: persist,dev
  application:
    name: e-welfare-settlement
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  configuration:
    default-statement-timeout: 180
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapperLocations: classpath:mapper/*.xml
  global-config:
    db-config:
      idType: AUTO
cbest:
  oss:
    config:
      accessKey: lF3iXaqMbr9f3GEdPJeN
      secretKey: KqMaYYENOqD8JBZUhqgBhOddVYc5Y1Pd1pAJRoA2
      keyPrefix: e-welfare/

exclude-header-interceptor:
  - /swagger*/**
  - /doc.html*
  - /error*
  - /index
  - /**/*.css
  - /**/*.js
  - /**/*.png
  - /**/*.jpg
  - /**/*.jpeg
  - /**/*.ico