spring:
  profiles: dev
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.1.30.186:3306/e-welfare-0208?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: mysql@123
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      maxActive: 20
      minIdle: 1
      testOnBorrow: true
      testOnReturn: false
      validationQuery: SELECT 1
  redis:
    lettuce:
      pool:
        max-idle: 30
        max-active: 8
        min-idle: 2
        max-wait: 1000
    timeout: 5000
    cluster:
      nodes:
        - 192.1.30.186:7000
        - 192.1.30.186:7001
        - 192.1.30.186:7002
        - 192.1.30.186:7003
        - 192.1.30.186:7004
        - 192.1.30.186:7005
    database: 0
  kafka:
    servers: 192.1.30.236:6667,192.1.30.237:6667,192.1.30.238:6667
    topic: test-order_info
    group-id: xx-test-e-welfare
    offset: earliest
#    latest
logging:
  file:
    path: D:/home/finance/Logs/e-welfare-settlement.e-cbest.lotest
  level:
    root: info
encrypt:
  file: ${config.file:classpath:config/config.properties}
e-welfare:
  distributed-lock:
    enabled: true
  account:
    url: http://127.0.0.1:10015
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

xxl:
  job:
    admin:
      addresses: http://172.30.37.35:8180/
    executor:
      appname: e-welfare-settlement
      ip:
      port: 9888
      logpath: /home/finance/Logs/e-welfare-settlement.e-cbest.lotest/jobhandler/
      logretentiondays: 30
    accessToken:
platformUser:
  url:

cbest:
  pay:
    url: http://192.1.30.71:9999/gateway
    appId: yufu
    appKey: e4716980da4382e1f4cc6ee4bb640277
    notifyUrl: http://xxx/accountDepositRecord/payNotify
  oss:
    config:
      bucket: sjgo-img-test
  dmall:
    url: http://172.30.37.22:4000
pos:
  onlines: 1001

cdn:
  server: http://img-test.sjgo365.com

merchant:
  url: http://172.30.37.188:10016

ftp:
  enabled: true
  host: paycheckftp.e-cbest.com
  port: 2112
  user: pay_tiancheng
  password: 4m+Hatccc
  default-path: /test

rocketmq:
  name-server: 172.30.37.35:9876;172.30.37.35:9876